---  
Resources:
  VPCPeering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref Fn::ImportValue:!Sub "${VPC1}-VPCID"
      PeerVpcId: !Ref Fn::ImportValue:!Sub "${VPC2}-VPC2"

  PeeringRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: Fn::ImportValue:!Sub "${VPC1}-VPCCIDR"
      RouteTableId: Fn::ImportValue:!Sub "${VPC1}-PrivateRouteTable"
      VpcPeeringConnectionId: !Ref VPCPeering

  PeeringRoute2:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: Fn::ImportValue:!Sub "${VPC2}-VPCCIDR"
      RouteTableId: Fn::ImportValue:!Sub "${VPC2}-PrivateRouteTable"
      VpcPeeringConnectionId: !Ref VPCPeering